includes/admin/post-types/meta-boxes/class-sp-meta-box-event-teams.php

Hi ThemeBoy,
Since yesterday, I have been testing out your Wonderful SportsPress plugin and it's just breathtaking in the sense that every time I told myself "aha, it lacks this feature", I found some minutes later that it did implement it and in a better way than I expected.
The only thing that I noticed (I think you just missed it by testing with a small set of 3 or 4 teams) is that when you have multiple divisons and competitions or different teams across seasons, you end up with a long list of teams.
So to make it more user friendly while creating an event, it will be good to filter the list of teams when one has selected the competition and the season.
The way it works with my fix is that you first create the event by setting the competition (league) and/or season and optionally the …

Filter teams by competition and season when creating an event.

---

feeds/ical.php

Made various enhancements/improvements to the iCal feed implementation. I have been testing and using these changes on TulsaRoustabouts.com for a few weeks without any issues and would love to share them with the greater SportsPress community. To see a feed currently using these changes, visit [this link](http://www.tulsaroustabouts.com/calendar/2016trfcfull?feed=sp-ical).
**Included commits:**
- Added new function to properly escape feed information that is not escaped [line 17]
- Added venue name to Address section [line 85]
- Added post content from events (currently only supports plain text data) to iCal item description [line 139]
- Fixed bug with iCal feed information not being properly escaped and thus losing any information after a non-escaped comma [lines 85, 138]
**Future …

iCal feed enhancements/improvements

---

includes/admin/class-sp-admin-assets.php
includes/class-sp-frontend-scripts.php

We run the admin in https and having the link to google being in http, causes insecure content warning in google chrome which blocks the code from working.   Therefore the editing of venue is broken when using the admin in https.

Removed hardcoded protocol for calls to google maps scripts

---

templates/event-calendar.php

If the the event-calendar ist put on the sidebar and a blog post from the past is viewed then the event-calendar will always show the past month by using the global vars $monthnum and $year from url.
To avoid this it is useful to override this behavior to show always the current month and year

override the global date in event-calendar.php template

---

includes/api/class-sp-rest-posts-controller.php
includes/api/class-sp-rest-terms-controller.php

In some cases (like users running older versions of WordPress), classes like `WP_REST_Posts_Controller` may not exist, thus creating Fatal Errors.
Here is an example.
https://wordpress.org/support/topic/plugin-conflict-154/

Avoid Fatal Errors when Core REST API classes don't exist.

---

templates/event-performance-table.php

Don't think that it needs to be described, but unclosed span-tag creates a new empty span after star icon http://take.ms/yFQ6U

fixes unclosed span in event-performance-table

---

includes/libraries/class-phpstack.php

`class-phpstack.php` was saved with ISO-8859-1 encoding, whereas the rest of the project uses UTF-8 encoding. This commit converts `class-phpstack.php` from ISO-8859-1 to UTF-8

Fix encoding error

---

includes/api/class-sp-rest-api.php
includes/api/class-sp-rest-players-controller.php
includes/api/class-sp-rest-posts-controller.php
includes/class-sp-post-types.php

To address #229 and #215 
Added an ability to filter the players by a team, current team or a past team.
Below will be the players filter HTTP requests:
* `wp-json/sportspress/v2/players/?team_id=TEAM_ID`
* `wp-json/sportspress/v2/players/?current_team_id=TEAM_ID`
* `wp-json/sportspress/v2/players/?past_team_id=TEAM_ID`
* `wp-json/sportspress/v2/players/?league=LEAGUE_NAME`
* `wp-json/sportspress/v2/players/?season=SEASON_NAME`
The above filters can also be use in conjunction to generate filter requests like:
* `wp-json/sportspress/v2/players/?team_id=TEAM_ID&season=SEASON_NAME&past_team_id=TEAM_ID`

Fix - Get players list by team, current team, past team, league and season

---

.gitignore
includes/shortcodes/class-sp-shortcode-staff.php
templates/staff-content.php
templates/staff-excerpt.php
templates/staff-header.php

Fix #179  - Make [staff] shortcode render the entire staff content including their name and profile (editor content).

Fix - Include staff name and profile in [staff] shortcode

---

includes/admin/settings/class-sp-settings-events.php
includes/sp-api-functions.php
modules/sportspress-lazy-loading.php

Added option to sort list of players (on the Teams metabox of Events) by Name or Jersey (default).

Event Player Checklist Sort Options

---

assets/css/sportspress-rtl.css

The RTL rule has no effect since [this rule in LTR](https://github.com/ThemeBoy/SportsPress/blob/742e3c9/assets/css/sportspress-style.css#L172-L174) takes precedence.
Related: Ticket [#15928](https://secure.helpscout.net/conversation/521620759/15928?folderId=287741)

Fix RTL CSS not working due to lower weight

---

wpml-config.xml

The option is `sportspress_footer_sponsors_title` and it appears in **Sportspress Settings > Settings**
There are other good candidates:
- Branding > Label
- League Menu > Title
Cheers,
Nabil
---
Reference: [Ticket #15893](https://secure.helpscout.net/conversation/520463000/15893?folderId=287736#thread-1420459816)

Add option to WPML config file

---

includes/sp-template-hooks.php

$terms can be False or WP_Error, in which case, the function will produce warnings. e.g.:
`Warning: uasort() expects parameter 1 to be array, boolean given in /var/html/wp-content/plugins/sportspress-pro/includes/sportspress/includes/sp-template-hooks.php on line 145`

Validate `sportspress_term_order()` parameter `$terms`

---

includes/class-sp-event.php

This fixes this recurring error: 
`Warning: array_filter() expects parameter 1 to be array, string given in /.../sportspress/includes/class-sp-event.php ... on line 20`

Prevent array_filter on non-array `$result`

---

includes/admin/importers/class-sp-player-importer.php

The problem is that when you have a player with a squad number of "0" in your players CSV file, this player is imported without an empty squad number. This should fix it.

Preserve squad number "0" when importing players

---

includes/admin/post-types/meta-boxes/class-sp-meta-box-staff-details.php

Hello,
This fixes this error:
` Warning: Invalid argument supplied for foreach() in /X/wp-includes/class-wp-list-util.php on line 148`
What happens is that [`wp_list_pluck()`](https://developer.wordpress.org/reference/functions/wp_list_pluck/) expects an array but is fed the result of [`get_terms()`](https://developer.wordpress.org/reference/functions/get_terms/) which is not sanitized, and `get_terms()` doesn't always return an array, sometimes it returns a boolean (`false`) and sometimes an object (`WP_Error` instance).

Make sure `wp_list_pluck()` is fed an array

---

includes/class-sp-event.php

Fixes a nasty error, see https://secure.helpscout.net/conversation/565362747/16858/.

Fix PHP Warning (Illegal string offset 'outcome')

---

includes/admin/importers/class-sp-player-importer.php

This fixes part of ticket 16802 where after and import, a player with multiple teams appears to having been imported correctly in the players listing page in the dashboard, but once you open the player page in the dashboard, the player's past teams field is empty.

Add past teams correctly when importing players

---

assets/css/admin.css

Improve stats visibility on the dashboard by reducing the lightness on automatic stats (from `gray` to `silver`).

Improve stats visibility on the dashboard

---

includes/class-sp-player-list.php

Fix PHP error `( ! ) Fatal error: Uncaught Error: Cannot unset string offsets in /var/www/public/wp-content/plugins/sportspress/includes/class-sp-player-list.php on line 532`

Fix PHP error

---

templates/player-list.php

When the player doesn't have a team, the player list shouldn't use the post title as the team name but should display nothing (empty string)

Fix team name in player list

---

includes/class-sp-calendar.php

Prevent filtering events with same teams but in reverse order (like second legs).
See ticket 19598

Do no filter relevant events

---

assets/js/admin/sportspress-admin.js

This patch fixes the bug with "chosen"-enabled dropdowns.
0. Open a player page in the dashboard
0. Close (collapse) the details metabox
0. Reload the page
0. Verify the dropdowns in the details metabox

Attach "chosen" to dropdowns correctly

---

templates/player-list.php

When grouping is enabled, icons appear only in the first table (see support ticket 20482)

Fix  icons in player list header

---

assets/js/sportspress.js

We don't need to worry about timezone, Date constructor is tricky, it does the conversions itself, the  conversion we need is already done in this line:
```
var countDownDate = new Date($(this).data('countdown')).getTime();
```

Fix timezone handling in countdowns

---

templates/event-performance-table.php
templates/event-performance.php

The staff table was added outside of the floating div(s), which breaks the output.
[Before](https://i.imgur.com/VVhKSNd.png) | [After](https://i.imgur.com/I0UWvSN.png).

Fix HTML for staff in event performance table

---

includes/admin/importers/class-sp-event-importer.php

Using generated event formats (i.e. `(new SP_Formats)->event`) instead of hard-coded ones allows the inclusion of custom formats added with [the `sportspress_formats` filter](https://github.com/ThemeBoy/SportsPress/blob/51e5ba02b25542a0a8bde497a05a80e9e2e5e9a9/includes/class-sp-formats.php#L25). 
Related ticket: 23122

Use generted instead of hardcoded event formats

---

templates/event-calendar.php

Some firewalls will remove $_SERVER['HTTP_USER_AGENT']. This causes the E_Notice

Prevent E_NOTICE

---

assets/js/sportspress.js

> The `.size()` method is deprecated as of jQuery 1.8. Use the `.length` property instead.
> 
> The `.size()` method is functionally equivalent to the `.length` property; however, **the `.length` property is preferred** because it does not have the overhead of a function call.
-- https://api.jquery.com/size/

Remove deprecated jQuery method `size()`

---

templates/event-list.php

How to reproduce error:
- Create a few events with different formats (competitive, tournament and friendly)
- Create a calendar and set the format filter to anything but "All"
- Notice that the filter is ignored and events of different formats are displayed 
Related ticket: 22358

Fix event lists ignoring the `format` parameter

---

templates/team-details.php

This image shows the error:
Props to Stefan on ticket 23127.

Fix multiple linked venues separator in team details

---

assets/js/admin/editor.js

On default WP theme 2020 I have sp_shortcodes_button error  https://1ce.org/1#HC5UJNmxN
Page builder https://wordpress.org/plugins/elementor/
Discuss: https://wordpress.org/support/topic/sp_shortcodes_button-error/#post-12944559

Fix Elementor compatibility

---

includes/api/class-sp-rest-api.php
includes/class-sp-player.php

To address #339
Remove array control on metrics data and add an autoconversion of PHP Object in PHP array.
For json request, i use the variable instead of label in metrics.
The variable names are lower case, without accent, without space (more stable than a label in a site).

The Metrics data are updatables by rest api

---

includes/class-sp-post-types.php

When a website uses a cache plugin like litespeed or memcache, the scheduled events pages didnt work. This is a possible fix.
https://wordpress.org/support/topic/match-overview-is-not-display/ 
https://wordpress.org/support/topic/sportspress-event-page-not-working-with-litespeed-cache-plugin/
https://wordpress.org/support/topic/all-sport-events-matches-showing-as-uncategorised/ https://wordpress.org/support/topic/sportspress-event-content-not-displaying/

Possible fix for blank pages with cache plugins

---

includes/class-sp-league-table.php

The error is:
```
Fatal error: Uncaught Error: Unsupported operand types: int + string
in /var/www/wp-content/plugins/sportspress-pro/includes/sportspress/includes/class-sp-league-table.php on line 396
```

Fix fatal error due to wrong type

---

templates/countdown.php

Avoid errors if not all needed variables are set when shortcode is being called by the user.

Fix: Undefined Variable $calendar in countdown.php
